# Generated by Django 6.0.2 on 2026-03-18 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_rename_customers_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='stripe_id',
            new_name='razorpay_id',
        ),
    ]
