# Generated by Django 6.0.2 on 2026-03-18 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_rename_stripe_id_customer_razorpay_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='razorpay_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
