# Generated by Django 6.0.2 on 2026-03-18 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_alter_customer_razorpay_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='razorpay_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
