# Generated by Django 6.0.2 on 2026-03-23 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_customer_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='init_email',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='init_email_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
