# Generated by Django 6.0.2 on 2026-03-23 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_customer_init_email_customer_init_email_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='init_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
