# Generated by Django 6.0.2 on 2026-03-12 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
            ],
            options={
                "permissions": [
                    ("premium", "Premium Perms"),
                    ("plus", "Plus Perm"),
                    ("free", "Free Perm"),
                ],
            },
        ),
    ]
