# Generated by Django 6.0.2 on 2026-03-27 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('subscriptions', '0007_alter_subscription_options_subscription_featured_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ['order', 'featured', '-updated'], 'permissions': [('premium', 'Premium Perms'), ('plus', 'Plus Perm'), ('custom', 'Custom Perm')]},
        ),
        migrations.AlterField(
            model_name='subscription',
            name='permissions',
            field=models.ManyToManyField(limit_choices_to={'codename__in': ['premium', 'plus', 'custom'], 'content_type__app_label': 'subscriptions'}, to='auth.permission'),
        ),
    ]
