# Generated by Django 6.0.2 on 2026-02-11 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visits", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pagevisit",
            name="path",
            field=models.TextField(blank=True, null=True),
        ),
    ]
